import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ApiUnknown} from '../src/api/client.ts';
import {RequirementCardGroups} from '../src/guide/card-groups.ts';
import {CardDrafts} from '../src/guide/card-drafts.ts';
const at='2026-10-06T06:00:00.000Z',option=key=>({option_key:key,label:key,description:'',impact:'',risks:''});
const definition={schema_version:1,intro:'问题',cards:[{card_key:'choice',card_type:'SINGLE_SELECT',question:'选择方案',context:'',required:true,options:[option('a'),option('b')],selection_rule:{min:1,max:1},custom_answer:{enabled:true,max_length:100},recommendation:{option_keys:['a'],reason:'仅展示'},related_spec_context:[]}]};
const message=(id,run=6,state='AVAILABLE')=>({id,requirement_id:1,guide_run_id:run,sequence_no:id,role:'ASSISTANT',content:'原问题'+id,message_type:'INTERACTION_CARDS',structured_content:definition,reply_to_message_id:null,created_at:at,card_state:state});
const source=(id=6)=>({id,requirement_id:1,action_type:'INITIALIZE',status:'COMPLETED'});
const detail=()=>({requirement:{id:1,status:'INITIALIZING',document_work_state:'IDLE',active_operation_type:null,active_operation_id:null},current:{id:2,requirement_id:1,document_type:'CURRENT',content_version:1},activity:{kind:'IDLE'}});
function fixture(items=[message(8)]){
 const listeners=new Set(),messageListeners=new Set(),f={parent:{detail:detail(),active:true,visible:true},messages:{items,loading:false,error:null},queries:[],fail:false,hold:false,release:null,sends:0,prepares:0,receives:0},memory=new Map();
 const notify=()=>{for(const listener of messageListeners)listener();},ai={getSnapshot:()=>f.parent,subscribe:listener=>{listeners.add(listener);return()=>listeners.delete(listener);},receive:async()=>{f.receives++;},messages:{getSnapshot:()=>f.messages,subscribe:listener=>{messageListeners.add(listener);return()=>messageListeners.delete(listener);},refresh:async()=>{notify();return true;}}};
 const api={getGuideRun:async id=>{f.queries.push(id);if(f.fail)throw Error('Unavailable');if(f.hold)return await new Promise(resolve=>f.release=()=>resolve({data:source(id)}));return {data:source(id)};},listMessages:async()=>({data:{items:f.messages.items},meta:{pagination:{page_size:20,next_cursor:null,has_more:false}}}),prepareCardResponses:()=>{f.prepares++;return {submit:async()=>{f.sends++;throw new ApiUnknown(true);}};}};
 const groups=new RequirementCardGroups(ai,api,new CardDrafts(()=>({getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value),removeItem:key=>memory.delete(key)})),async()=>f.parent.detail,async()=>{});groups.setAvailable(true);
 return {f,ai,api,groups,memory,update(next){f.messages={...f.messages,items:next};notify();},hide(visible){f.parent={...f.parent,visible};for(const listener of listeners)listener();}};
}
test('actual message groups keep independent local drafts and original timeline identities without recommended defaults',async()=>{
 const {groups,memory,update}=fixture([message(8,6,'EXPIRED'),message(10,7)]);assert(await groups.ready());const first=groups.get(8).owner,last=groups.get(10).owner;assert(!first.editable);assert.deepEqual(last.getSnapshot().answers.responses[0].selected_option_keys,[]);last.custom('choice','保留😀');assert.equal(memory.size,1);update([message(8,6,'EXPIRED'),message(10,7)]);assert(await groups.ready());assert.equal(groups.get(10).owner,last);assert.equal(last.getSnapshot().answers.responses[0].custom_answer,'保留😀');assert.deepEqual(groups.getSnapshot().slots.map(slot=>slot.message_id),[8,10]);groups.dispose();
});
test('real I35 EXPIRED clears exactly that draft; another group stays independent and unavailable old controls never reappear',async()=>{
 const {groups,memory,update}=fixture();await groups.ready();const old=groups.get(8).owner;old.custom('choice','原草稿');update([message(8,6,'EXPIRED'),message(10,7)]);await groups.ready();const current=groups.get(10).owner;current.custom('choice','新草稿');assert.equal(memory.size,1);assert.equal(old.getSnapshot().message.card_state,'EXPIRED');assert(old.getSnapshot().answers.responses.every(answer=>answer.custom_answer===null));assert.equal(current.getSnapshot().answers.responses[0].custom_answer,'新草稿');groups.dispose();
});
test('own UNKNOWN remains the same owner and original immutable action through actual ANSWERED messages and new groups',async()=>{
 const {groups,f,update,memory}=fixture();await groups.ready();const owner=groups.get(8).owner;owner.toggle('choice','b',true);assert(!await owner.submit());assert.equal(owner.getSnapshot().phase,'UNKNOWN');const formal={id:9,requirement_id:1,guide_run_id:7,sequence_no:9,role:'USER',content:'选择方案\nb',message_type:'CARD_RESPONSE',structured_content:{schema_version:1,responses:[{card_key:'choice',selected_option_keys:['b'],custom_answer:null,skipped:false}]},reply_to_message_id:8,created_at:at,card_state:null};
 update([message(8,6,'ANSWERED'),formal,message(10,8)]);assert(await groups.ready());assert.equal(groups.get(8).owner,owner);assert.equal(owner.getSnapshot().phase,'UNKNOWN');assert.equal(owner.getSnapshot().formal.id,9);assert.equal(memory.size,0);assert.equal(f.prepares,1);assert.equal(f.sends,1);assert.equal(f.receives,0);assert.deepEqual(owner.getSnapshot().submitted.responses[0].selected_option_keys,['b']);groups.dispose();
});
test('source read failure retains existing draft/owner, disables writes and retries the actual source',async()=>{
 const {groups,f,update}=fixture();await groups.ready();const owner=groups.get(8).owner;owner.custom('choice','仍在');f.fail=true;update([message(8,6,'AVAILABLE'),message(10,7)]);assert(!await groups.ready());assert.equal(groups.get(8).owner,owner);assert.equal(owner.getSnapshot().answers.responses[0].custom_answer,'仍在');assert(!owner.allowed);assert(groups.get(8).error);f.fail=false;assert(await groups.retry());assert.equal(groups.get(8).owner,owner);assert(owner.allowed);groups.dispose();
});
test('damaged history has no interactive slot, keeps its readable article and never exposes a retained stale owner',async()=>{
 const {groups,update,hide}=fixture();await groups.ready();const owner=groups.get(8).owner;owner.custom('choice','保留在当前内存');update([{...message(8),structured_content:null,card_state:null}]);await groups.ready();assert.equal(groups.get(8),null);assert(!owner.allowed);hide(false);hide(true);await groups.ready();assert(!owner.allowed);groups.dispose();
});
test('late source reads cannot resurrect hidden or retired groups; reopen retries actual facts',async()=>{
 const {groups,f,update,hide}=fixture();await groups.ready();f.hold=true;update([message(8),message(10,7)]);for(let i=0;i<10;i++)await Promise.resolve();hide(false);f.release();assert(!await groups.ready());assert.equal(groups.get(10)?.owner??null,null);f.hold=false;hide(true);assert(await groups.ready());assert(groups.get(10).owner);const owner=groups.get(8).owner;owner.custom('choice','最后输入');groups.dispose();assert.equal(owner.getSnapshot().active,false);assert(!await owner.submit());
});
test('a newer actual message cohort supersedes an unfinished source read without clearing the old local input',async()=>{
 const {groups,f,update}=fixture();await groups.ready();const original=groups.get(8).owner;original.custom('choice','原输入');f.hold=true;update([message(8),message(10,7)]);for(let i=0;i<10;i++)await Promise.resolve();update([message(8,6,'EXPIRED'),message(12,9)]);f.hold=false;f.release();assert(await groups.ready());assert.equal(groups.get(10),null);assert(groups.get(12).owner);assert.equal(original.getSnapshot().message.card_state,'EXPIRED');assert.equal(f.prepares,0);groups.dispose();
});
test('accepted answers are not undone by an older AVAILABLE message window finishing late',async()=>{
 const {groups,api,f,update}=fixture();const originalMessage=message(8);api.prepareCardResponses=(_id,answers)=>({submit:async()=>({data:{card_state:'ANSWERED',guide_run:{id:7,requirement_id:1,status:'RUNNING',current_step:'PREPARING'},response_message:{id:9,requirement_id:1,guide_run_id:7,sequence_no:9,role:'USER',message_type:'CARD_RESPONSE',reply_to_message_id:8,created_at:at,card_state:null,content:'选择方案\nb',structured_content:answers}}})});await groups.ready();const owner=groups.get(8).owner;owner.toggle('choice','b',true);assert(!await owner.submit());assert.equal(owner.getSnapshot().phase,'CONFIRMED');assert.equal(owner.getSnapshot().message.card_state,'ANSWERED');update([originalMessage,message(10,8)]);await groups.ready();assert.equal(owner.getSnapshot().message.card_state,'ANSWERED');assert.equal(owner.getSnapshot().formal.id,9);assert.equal(owner.getSnapshot().phase,'CONFIRMED');assert.equal(f.receives,1);groups.dispose();
});
