import {test} from 'node:test';
import assert from 'node:assert/strict';
import {ApiUnknown} from '../src/api/client.ts';
import {RequirementConversation} from '../src/guide/conversation-owner.ts';
import {CardDrafts} from '../src/guide/card-drafts.ts';
const at='2026-10-06T07:00:00.000Z',copy=value=>structuredClone(value);
const run=(id=6,status='COMPLETED')=>({id,requirement_id:1,status,current_step:status==='WAITING_USER'?'WAITING_USER':'FINISHED',action_type:'INITIALIZE',function_type:'INITIALIZE',created_at:at,scope:{scope_type:'DOCUMENT',scope_ref:null},suggestion_batch_id:null,latest_assistant_message_id:8,final_result:null});
const detail=()=>({requirement:{id:1,status:'INITIALIZING',document_work_state:'IDLE',active_operation_type:null,active_operation_id:null},current:{id:2,requirement_id:1,document_type:'CURRENT',content_version:1,markdown_content:'原正文\n',block_state_json:{blocks:[],schema_version:1,next_block_id:1}},activity:{kind:'IDLE'},comment_index:{}});
const cards={schema_version:1,intro:'正式端口卡片',cards:[{card_key:'choice',card_type:'SINGLE_SELECT',question:'明确选择',context:'',required:true,options:['a','b'].map(option_key=>({option_key,label:option_key,description:'',impact:'',risks:''})),selection_rule:{min:1,max:1},custom_answer:{enabled:true,max_length:100},recommendation:{option_keys:['a'],reason:'仅参考'},related_spec_context:[]}]};
const message=()=>({id:8,requirement_id:1,guide_run_id:6,sequence_no:1,role:'ASSISTANT',content:'正式端口卡片',message_type:'INTERACTION_CARDS',structured_content:cards,reply_to_message_id:null,created_at:at,card_state:'AVAILABLE'});
function fixture(){
 const f={detail:detail(),messages:[message()],runs:[run()],prepares:0,sends:0,reads:0,queries:0,adopts:0,opens:0,drop:false,readFail:false,adoptFail:false,batch:null,batchQueries:0},memory=new Map();
 const actual=async()=>{f.reads++;if(f.readFail)throw Error('Read failure');return copy(f.detail);};
 const prepare=(kind,body)=>{f.prepares++;const frozen=copy(body);let receipt;return {submit:async()=>{f.sends++;if(!receipt){if(kind==='DECIDE'){const item=f.batch.suggestions[0];item.status=frozen.decision;item.user_edited_content=frozen.edited_content;item.decided_at=at;f.batch.counts={total:1,pending:0,accepted:1,rejected:0,edited:0};receipt={suggestion:copy(item),counts:copy(f.batch.counts)};}
  else{f.runs.unshift(run(7,'FAILED'));if(kind==='TEXT'){f.messages[0]={...f.messages[0],card_state:'EXPIRED'};receipt={guide_run:{id:7,requirement_id:1,status:'RUNNING',current_step:'PREPARING'},user_message:{id:9,requirement_id:1,guide_run_id:7,role:'USER',message_type:'TEXT',content:frozen.instruction}};f.messages.push({...receipt.user_message,sequence_no:2,created_at:at,structured_content:null,reply_to_message_id:null,card_state:null});}
  else{f.messages[0]={...f.messages[0],card_state:'ANSWERED'};const formal={id:9,requirement_id:1,guide_run_id:7,sequence_no:2,role:'USER',content:'明确选择\nb',message_type:'CARD_RESPONSE',structured_content:frozen,reply_to_message_id:8,created_at:at,card_state:null};f.messages.push(formal);receipt={card_state:'ANSWERED',guide_run:{id:7,requirement_id:1,status:'RUNNING',current_step:'PREPARING'},response_message:formal};}}
 }if(f.drop){f.drop=false;throw new ApiUnknown(true);}return {data:copy(receipt)};}};};
 const api={getGuideRun:async id=>{f.queries++;return {data:copy(f.runs.find(row=>row.id===id))};},listMessages:async()=>({data:{items:copy(f.messages)},meta:{pagination:{page_size:20,has_more:false,next_cursor:null}}}),listGuideRuns:async()=>({data:{items:copy([...f.runs].sort((a,b)=>b.id-a.id))},meta:{pagination:{page:1,page_size:20,total:f.runs.length,total_pages:1}}}),getBatch:async id=>{f.batchQueries++;assert.equal(id,8);return {data:copy(f.batch)};},prepareCreateGuide:(_id,body)=>prepare('TEXT',body),prepareCardResponses:(_id,body)=>prepare('CARD',body),prepareDecideSuggestion:(_id,body)=>prepare('DECIDE',body)};
 const owner=new RequirementConversation(f.detail,api,actual,async()=>{f.adopts++;if(f.adoptFail){f.adoptFail=false;throw Error('Adoption failed');}},()=>{f.opens++;owner.setView(true);},new CardDrafts(()=>({getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value),removeItem:key=>memory.delete(key)})));
 return {f,owner,actual,memory};
}
const ready=async owner=>{owner.setView(true);await owner.refresh();await owner.cards.ready();};
test('ordinary text shares receiver/messages and only actual EXPIRED clears that card draft; UNKNOWN excludes sibling writes across hide',async()=>{
 const {f,owner,memory}=fixture();await ready(owner);const card=owner.cards.get(8).owner;card.custom('choice','未提交😀');owner.composer.change('普通文字，不能映射成选项');f.drop=true;assert(!await owner.composer.submit());assert.equal(owner.getSnapshot().lease,'COMPOSER');assert(!card.allowed);assert.equal(memory.size,1);owner.setView(false);assert(!await owner.composer.recover());owner.setView(true);await owner.read.refresh();assert.equal(card.getSnapshot().message.card_state,'EXPIRED');assert.equal(memory.size,0);assert.equal(owner.getSnapshot().lease,'COMPOSER');assert.equal(owner.composer.getSnapshot().instruction,'普通文字，不能映射成选项');assert(await owner.composer.recover());assert.equal(f.prepares,1);assert.equal(f.sends,2);assert.equal(owner.read.getSnapshot().selected,7);assert.equal(owner.read.getSnapshot().run.status,'FAILED');assert.equal(owner.composer.getSnapshot().instruction,'');assert.equal(owner.getSnapshot().lease,null);assert.equal(owner.read.messages.getSnapshot().items[1].message_type,'TEXT');owner.dispose();
});
test('retained card submission prevents ordinary/Run actions and keeps original owner through source/message refresh',async()=>{
 const {f,owner}=fixture();await ready(owner);const card=owner.cards.get(8).owner;card.toggle('choice','b',true);f.drop=true;assert(!await card.submit());assert.equal(owner.getSnapshot().lease,'CARD:8');assert(!owner.composer.allowed);assert(!owner.runs.getSnapshot().available);assert(!await owner.composer.submit());assert.equal(f.prepares,1);await owner.read.refresh();await owner.cards.ready();assert.equal(owner.cards.get(8).owner,card);assert.equal(card.getSnapshot().phase,'UNKNOWN');assert.equal(owner.getSnapshot().lease,'CARD:8');assert(await card.recover(),JSON.stringify(card.getSnapshot()));assert.equal(f.prepares,1);assert.equal(f.sends,2);assert.equal(owner.getSnapshot().lease,null);assert.equal(owner.read.getSnapshot().selected,7);owner.dispose();
});
test('CONFIRMED adopts once after pure reads, own document busy never breaks availability, readonly/hidden restores preserved input',async()=>{
 const {f,owner}=fixture();await ready(owner);owner.composer.change('  原始输入  ');f.adoptFail=true;assert(!await owner.composer.submit());assert.equal(owner.composer.getSnapshot().phase,'CONFIRMED');assert.equal(owner.getSnapshot().lease,'COMPOSER');assert(owner.composer.getSnapshot().available);owner.setView(true,false);assert(!owner.read.getSnapshot().visible);assert(!await owner.composer.finish());assert.equal(owner.composer.getSnapshot().instruction,'  原始输入  ');owner.setView(true,true);assert(await owner.composer.finish());assert.equal(f.prepares,1);assert.equal(f.sends,1);assert.equal(f.opens,1);owner.dispose();
});
test('actual activity batch is loaded once without fake empty, retained decision pins original batch across competing actual activity',async()=>{
 const {f,owner}=fixture();f.batch={id:8,requirement_id:1,guide_run_id:6,source_type:'USER_INSTRUCTION',source_id:null,title:'批次',summary:'正式端口前置',status:'PENDING',completion_result:null,error_message:null,base_content_version:1,applied_content_version:null,created_at:at,completed_at:null,updated_at:at,suggestions:[{id:10,batch_id:8,order_no:1,title:'规则',explanation:'明确',impact:null,patch_operation:'REPLACE_BLOCK',target_ref:{block_id:1},selector:null,original_content:'原正文\n',proposed_markdown:'新正文\n',proposed_data:null,user_edited_content:null,status:'PENDING',validation_status:'VALID',validation_error:null,created_at:at,decided_at:null,updated_at:at}],counts:{total:1,pending:1,accepted:0,rejected:0,edited:0}};
 f.detail={...f.detail,requirement:{...f.detail.requirement,status:'ACTIVE',document_work_state:'SUGGESTION_REVIEWING',active_operation_type:'SUGGESTION_BATCH',active_operation_id:8},activity:{kind:'BATCH',batch:copy(f.batch)}};owner.adopt(f.detail);owner.setView(true);const batch=owner.getSnapshot().batch;assert(batch);assert(await batch.refresh());assert.equal(owner.batch(8),batch);f.drop=true;assert(!await batch.decide(10,'ACCEPTED'));assert.equal(owner.getSnapshot().lease,'BATCH:8');assert(!owner.composer.getSnapshot().available);owner.setView(false);owner.adopt({...detail(),requirement:{...detail().requirement,status:'ACTIVE'}});owner.setView(true);assert.equal(owner.getSnapshot().batch,batch);assert.equal(batch.getSnapshot().phase,'UNKNOWN');f.readFail=true;assert(!await batch.recover());assert.equal(f.sends,1);f.readFail=false;assert(await batch.recover(),JSON.stringify(batch.getSnapshot()));assert.equal(f.prepares,1);assert.equal(f.sends,2);owner.dispose();
});
test('actual history selection remains separate from ordinary current scope and does not manufacture a pending batch',async()=>{
 const {owner,f}=fixture();await ready(owner);owner.composer.change('未发送');owner.read.open({...f.runs[0],status:'COMPLETED'});await owner.read.refresh();assert.equal(owner.read.getSnapshot().selection,'HISTORY');assert.equal(owner.composer.getSnapshot().instruction,'未发送');assert.equal(owner.composer.getSnapshot().target.document_id,2);assert.equal(owner.getSnapshot().batch,null);assert.equal(f.batchQueries,0);owner.dispose();
});
test('retirement closes all owners, observers and pending unstarted operations without mutations',async()=>{
 const {f,owner}=fixture();await ready(owner);const card=owner.cards.get(8).owner;owner.composer.change('末尾输入');owner.dispose();assert.equal(owner.getSnapshot().active,false);assert.equal(card.getSnapshot().active,false);assert(!await owner.composer.submit());assert(!await card.submit());assert.equal(f.prepares,0);assert.equal(f.sends,0);assert.equal(owner.read.getSnapshot().visible,false);
});
