"""Review-only resource/DDL checks; never opens a user's runtime database.

Uses the already available jsonschema checker, records its actual version. This
is structural draft validation, not application integration or model evaluation.
"""
import copy
import hashlib
import importlib.metadata
import json
from pathlib import Path
import sqlite3
import tempfile
from datetime import datetime, timezone

from jsonschema import Draft202012Validator

ROOT = Path(__file__).resolve().parents[1]
PROPOSALS = ROOT / 'docs' / 'proposals'
RESOURCES = PROPOSALS / 'resources-v1'
checks = []


def check(name, condition):
    if not condition:
        raise AssertionError(name)
    checks.append(name)


manifest = json.loads((RESOURCES / 'manifest.json').read_text(encoding='utf-8'))
check('resource manifest remains explicitly unapproved', manifest['status'] == 'UNAPPROVED_PROPOSAL')
for entry in manifest['files']:
    content = (RESOURCES / entry['path']).read_bytes()
    check('manifest hash: ' + entry['path'], hashlib.sha256(content).hexdigest() == entry['sha256'])
    check('manifest bytes: ' + entry['path'], len(content) == entry['bytes'])

schemas = {}
for path in sorted((RESOURCES / 'schemas').glob('*.json')):
    value = json.loads(path.read_text(encoding='utf-8'))
    Draft202012Validator.check_schema(value)

    def inspect(node):
        if isinstance(node, dict):
            if node.get('type') == 'object':
                check(f'{path.name} object disallows extra fields', node.get('additionalProperties') is False)
            if '$ref' in node:
                check(f'{path.name} reference resolves: {node["$ref"]}', node['$ref'].startswith('#/$defs/') and node['$ref'][8:] in value['$defs'])
            for child in node.values():
                inspect(child)
        elif isinstance(node, list):
            for child in node:
                inspect(child)
    inspect(value)
    schemas[path.name.split('.')[0]] = Draft202012Validator(value)
check('six inputs and four shared outputs', len(schemas) == 10)

# Independent examples; no sample is generated by the candidate Schema.
option = {'option_key': 'yes', 'label': '是', 'description': '', 'impact': '', 'risks': ''}
card = {'card_key': 'c1', 'card_type': 'CONFIRM', 'question': '是否已确定？', 'context': '', 'required': True, 'options': [option, {**option, 'option_key': 'no', 'label': '否'}], 'selection_rule': {'min': 1, 'max': 1}, 'custom_answer': {'enabled': False, 'max_length': 0}, 'recommendation': None, 'related_spec_context': []}
cards = {'schema_version': 1, 'intro': '请确认', 'cards': [card]}
patch = {'title': '明确审批人', 'explanation': '用户明确补充', 'impact': None, 'target_ref': {'block_id': 2}, 'original_content': '待确认。', 'patch_operation': 'REPLACE_BLOCK', 'selector_json': None, 'proposed_markdown': '审批人为部门经理。', 'proposed_data_json': None}


def sample(response_type, **fields):
    return {'schema_version': 1, 'response_type': response_type, 'message': '已处理', **fields}


examples = {
    'INITIALIZE_OUTPUT': [sample('INITIALIZE_TEXT', confirmed_fact_patches=[]), sample('INITIALIZE_CARDS', cards=cards, confirmed_fact_patches=[{'patch': patch, 'evidence': [{'message_id': 601, 'quoted_text': '审批人为部门经理'}]}])],
    'ASK_OUTPUT': [sample('ANSWER'), sample('CLARIFY_TEXT'), sample('CLARIFY_CARDS', cards=cards)],
    'REVIEW_OUTPUT': [sample('REVIEW_RESULT', review_result={'schema_version': 1, 'summary': '未发现问题', 'issues': []}), sample('CLARIFY_TEXT'), sample('CLARIFY_CARDS', cards=cards)],
    'MODIFY_OUTPUT': [sample('NO_CHANGE'), sample('SUGGESTIONS', title='明确审批人', summary='补充明确规则', suggestions=[patch]), sample('CLARIFY_TEXT'), sample('CLARIFY_CARDS', cards=cards)],
}
for name, values in examples.items():
    for value in values:
        schemas[name].validate(value)
        check(name + ' legal independent branch: ' + value['response_type'], True)
        invalid = {**value, 'unknown': 'must not be ignored'}
        check(name + ' rejects root extra field', not schemas[name].is_valid(invalid))
        invalid = {key: content for key, content in value.items() if key != 'message'}
        check(name + ' rejects missing required field', not schemas[name].is_valid(invalid))
        check(name + ' rejects bool schema version', not schemas[name].is_valid({**value, 'schema_version': True}))
    check(name + ' rejects another task branch', not schemas[name].is_valid(sample('UNREGISTERED_BRANCH')))
invalid = copy.deepcopy(examples['INITIALIZE_OUTPUT'][1])
invalid['cards']['cards'][0]['options'][0]['extra'] = 'x'
check('nested card option extras rejected', not schemas['INITIALIZE_OUTPUT'].is_valid(invalid))
invalid = copy.deepcopy(examples['MODIFY_OUTPUT'][1])
invalid['suggestions'] = []
check('empty suggestion batch rejected', not schemas['MODIFY_OUTPUT'].is_valid(invalid))
invalid = copy.deepcopy(examples['MODIFY_OUTPUT'][1])
invalid['suggestions'][0]['patch_operation'] = 'DELETE_BLOCK'
check('DELETE proposal fields rejected', not schemas['MODIFY_OUTPUT'].is_valid(invalid))

functions = json.loads((RESOURCES / 'functions.v1.json').read_text(encoding='utf-8'))['functions']
for function in functions:
    source_type = function['source_type']
    source = None
    if source_type == 'REVIEW_RESULT':
        source = {'guide_run_id': 500, 'reviewed_content_version': 2, 'review_result': {'schema_version': 1, 'summary': '需补审批人', 'issues': []}}
    if source_type == 'COMMENT':
        source = {'comment_id': 901, 'content': '请说明审批人', 'anchor_type': 'BLOCK', 'block_id': 2, 'anchor_ref': {'block_markdown_snapshot': '待确认。'}, 'current_location': None}
    input_value = {
        'schema_version': 1, 'function_type': function['function_type'], 'action_type': function['action_type'], 'source_type': source_type,
        'requirement': {'id': 101, 'requirement_no': 'REQ000001', 'requirement_type': 'NEW', 'title': '需求甲', 'status': 'INITIALIZING' if function['action_type'] == 'INITIALIZE' else 'ACTIVE', 'initialization_mode': 'IDEATION'},
        'current_document': {'id': 201, 'content_version': 3, 'read_blocks': []},
        'template': {'template_key': 'new-requirement', 'template_version': 'v1', 'markdown_content': '# 需求新增规格\n', 'locked_heading_block_ids': []},
        'scope': {'scope_type': 'DOCUMENT', 'scope_ref': None}, 'allowed_targets': [],
        'user_input': {'message_id': 601, 'content': '整理需求', 'formal_responses': None}, 'history': [], 'source': source,
        'read_manifest': {'document_id': 201, 'content_version': 3, 'block_ids': [], 'message_ids': [601], 'template': {'key': 'new-requirement', 'version': 'v1'}, 'source': {'source_type': source_type, 'source_id': None if source is None else source.get('comment_id', source.get('guide_run_id'))}, 'context_template': {'key': function['context_template'].split('@')[0], 'version': 'v1'}, 'prompt': {'key': function['function_type'], 'version': 'v1'}, 'function_type': function['function_type']},
    }
    validator = schemas[function['input_schema'].split('@')[0]]
    validator.validate(input_value)
    check(function['function_type'] + ' input structure example only (not business context proof)', True)
    check(function['function_type'] + ' source mismatch rejected', not validator.is_valid({**input_value, 'source': {} if source is None else None}))

field_map = json.loads((PROPOSALS / 'storage-field-map.json').read_text(encoding='utf-8'))
table_names = {'Requirement': 'requirements', 'RequirementDocument': 'requirement_documents', 'Revision': 'revisions', 'ConversationMessage': 'conversation_messages', 'GuideRun': 'guide_runs', 'LLMUse': 'llm_uses', 'SuggestionBatch': 'suggestion_batches', 'Suggestion': 'suggestions', 'Comment': 'comments'}
with tempfile.TemporaryDirectory(prefix='walle-proposal-check-') as directory:
    database = sqlite3.connect(str(Path(directory) / 'draft.sqlite'))
    database.execute('PRAGMA foreign_keys=ON')
    database.executescript((PROPOSALS / 'storage-v1.sql').read_text(encoding='utf-8'))
    for entity, fields in field_map['entities'].items():
        columns = {row[1]: row for row in database.execute(f'PRAGMA table_info({table_names[entity]})')}
        check(entity + ' all source persistent fields represented', all(field['name'] in columns for field in fields))
        check(entity + ' source nullable/required mapping preserved', all(bool(columns[field['name']][3]) is not field['nullable'] for field in fields))
    llm_columns = {row[1]: row for row in database.execute('PRAGMA table_info(llm_uses)')}
    check('provider request id explicit draft TEXT override', llm_columns['provider_request_id'][2] == 'TEXT')
    req = {'id': 101, 'requirement_no': 'REQ000001', 'requirement_type': 'NEW', 'initialization_mode': 'IDEATION', 'title': '需求甲', 'template_key': 'new-requirement', 'template_version': 'v1', 'status': 'ACTIVE', 'document_work_state': 'IDLE', 'active_operation_type': None, 'active_operation_id': None, 'created_at': '2026-09-21T08:30:00.000Z', 'updated_at': '2026-09-21T08:30:00.000Z', 'completed_at': None, 'state_started_at': None}
    database.execute('INSERT INTO requirements (' + ','.join(req) + ') VALUES (' + ','.join('?' for _ in req) + ')', list(req.values()))
    for column, value in [('id', 102), ('requirement_no', 'REQ000002'), ('document_work_state', 'MANUAL_EDITING')]:
        try:
            database.execute(f'UPDATE requirements SET {column}=? WHERE id=101', (value,))
        except sqlite3.IntegrityError:
            check('draft rejects invalid update: ' + column, True)
        else:
            raise AssertionError('Invalid requirement update accepted: ' + column)
    try:
        database.execute("UPDATE requirements SET document_work_state='MANUAL_EDITING',active_operation_id=202,state_started_at='2026-09-21T08:30:00.000Z',active_operation_type=NULL WHERE id=101")
    except sqlite3.IntegrityError:
        check('SQL NULL cannot bypass active type condition', True)
    else:
        raise AssertionError('NULL active type bypassed SQL CHECK')
    database.close()

record = {'scope': 'UNAPPROVED draft Schema/manifest/DDL structure only; not business acceptance, production adoption, or AI quality', 'recorded_at': datetime.now(timezone.utc).isoformat(), 'sqlite': sqlite3.sqlite_version, 'jsonschema_checker': importlib.metadata.version('jsonschema'), 'checks': checks, 'passed': True, 'content_hashes': {str(path.relative_to(PROPOSALS)).replace('\\', '/'): hashlib.sha256(path.read_bytes()).hexdigest() for path in sorted(PROPOSALS.rglob('*')) if path.is_file() and path.name not in ('review-manifest.json', '集中确认清单.md')}}
evidence = ROOT / 'docs/verification/proposals-v1.json'
evidence.write_text(json.dumps(record, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print(json.dumps({'passed': True, 'check_count': len(checks), 'scope': record['scope'], 'evidence': str(evidence)}, ensure_ascii=False))
